# Generated by Django 5.0.6 on 2024-05-14 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('days_creation_below_operational_hour', models.IntegerField()),
                ('days_creation_above_operational_hour', models.IntegerField()),
                ('days_creation_below_operational_hour_reinvestment', models.IntegerField()),
                ('days_creation_above_operational_hour_reinvestment', models.IntegerField()),
                ('operational_hour', models.TimeField()),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
